# Testing alpine:
FROM alpine:latest AS alpine_tester
COPY deploy-s6-overlay.sh /src/deploy-s6-overlay.sh
RUN apk update && \
    apk add \
      file \
      gnupg \
      && \
    file $(which file) && \
    /src/deploy-s6-overlay.sh

# Testing Debian
FROM debian:stable-slim AS debian_tester
COPY --from=0 /bin/cp /tmp/_deleteme
COPY deploy-s6-overlay.sh /src/deploy-s6-overlay.sh
RUN apt-get update && \
    apt-get install -y \
      ca-certificates \
      curl \
      file \
      gnupg \
      && \
    file $(which file) && \
    /src/deploy-s6-overlay.sh
