# Testing alpine:
FROM alpine:latest AS alpine_tester
COPY deploy-s6-overlay.sh /src/deploy-s6-overlay.sh
RUN apk --no-cache add \
      file \
      gnupg \
      > /dev/null 2>&1 && \
    file "$(which file)" && \
    /src/deploy-s6-overlay.sh

# Testing Debian
FROM debian:stable-slim AS debian_tester
COPY --from=0 /bin/cp /tmp/_deleteme
COPY deploy-s6-overlay.sh /src/deploy-s6-overlay.sh
RUN apt-get update > /dev/null 2>&1 && \
    apt-get install -y \
      ca-certificates \
      curl \
      file \
      gnupg \
      > /dev/null 2>&1 && \
    file "$(which file)" && \
    /src/deploy-s6-overlay.sh
